BOARD_TAG = uno
MONITOR_PORT = /dev/ttyAMA0
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=/usr/share/arduino
AVR_TOOLS_DIR=/usr
AVRDUDE=/usr/bin/avrdude
AVRDUDE_CONF=/etc/avrdude.conf
RESET_CMD=./reset.sh

include $(ARDMK_DIR)/Arduino.mk #include the Makefile
